"""Dependency-boundary tests for split-capture alignment policy."""

import subprocess
import sys


def test_split_alignment_policy_import_does_not_load_the_concrete_sane_backend() -> None:
    script = """
import sys
from coolscanpy.transport.split_alignment_policy import (
    SPLIT_MAX_ECC_DIVERGENCE_PX,
    SPLIT_MAX_ECC_REFINEMENT_DELTA_PX,
    SPLIT_MAX_HORIZONTAL_SHIFT_PX,
    SPLIT_MAX_VERTICAL_SHIFT_PX,
    SPLIT_MAX_CHANNEL_SPREAD_PX,
    SPLIT_MIN_ECC,
    SPLIT_MIN_OVERLAP_FRACTION,
    SPLIT_MIN_PHASE_RESPONSE,
    SPLIT_MIN_TEXTURE_STD,
    SPLIT_MULTISCALE_HIGH_MAX_DIMENSION,
    SPLIT_MULTISCALE_HIGH_MIN_RESPONSE,
    SPLIT_MULTISCALE_LOW_MAX_DIMENSION,
    SPLIT_MULTISCALE_LOW_MIN_RESPONSE,
    SPLIT_MULTISCALE_MAX_CHANNEL_SHIFT_PX,
    SPLIT_MULTISCALE_MAX_CHANNEL_SPREAD_PX,
    SPLIT_MULTISCALE_MAX_CROSS_SCALE_DELTA_PX,
    SPLIT_MULTISCALE_MIN_ASPECT_RATIO,
    SPLIT_MULTISCALE_PERIODIC_ALIAS_DOMINANCE,
    SPLIT_MULTISCALE_PERIODIC_ALIAS_MIN_CHANNELS,
    SPLIT_MULTISCALE_PERIODIC_ALIAS_MIN_HORIZONTAL_PX,
    SPLIT_PHASE_ONLY_MAX_CHANNEL_SPREAD_PX,
    SPLIT_PHASE_ONLY_MAX_SHIFT_PX,
    SPLIT_PHASE_ONLY_MIN_RESPONSE,
    SPLIT_TILED_PHASE_MAX_CHANNEL_SPREAD_PX,
    SPLIT_TILED_PHASE_MAX_SHIFT_PX,
    SPLIT_TILED_PHASE_MAX_TILE_SPREAD_PX,
    SPLIT_TILED_PHASE_MIN_MEDIAN_RESPONSE,
    SPLIT_TILED_PHASE_MIN_SUPPORT,
    SPLIT_TILED_PHASE_MIN_TILE_RESPONSE,
)

assert SPLIT_MIN_PHASE_RESPONSE == 0.10
assert SPLIT_MAX_CHANNEL_SPREAD_PX == 1.0
assert SPLIT_MIN_ECC == 0.65
assert SPLIT_MAX_ECC_DIVERGENCE_PX == 2.0
assert SPLIT_MAX_ECC_REFINEMENT_DELTA_PX == 0.5
assert SPLIT_MAX_ECC_REFINEMENT_DELTA_PX < SPLIT_MAX_ECC_DIVERGENCE_PX
assert SPLIT_MAX_HORIZONTAL_SHIFT_PX == 2.0
assert SPLIT_MAX_VERTICAL_SHIFT_PX == 8.0
assert SPLIT_MIN_TEXTURE_STD == 1e-4
assert SPLIT_MIN_OVERLAP_FRACTION == 0.5
assert SPLIT_PHASE_ONLY_MIN_RESPONSE == 0.50
assert SPLIT_PHASE_ONLY_MAX_CHANNEL_SPREAD_PX == 0.10
assert SPLIT_PHASE_ONLY_MAX_SHIFT_PX == 2.0
assert SPLIT_TILED_PHASE_MIN_TILE_RESPONSE == 0.30
assert SPLIT_TILED_PHASE_MIN_MEDIAN_RESPONSE == 0.40
assert SPLIT_TILED_PHASE_MIN_SUPPORT == 6
assert SPLIT_TILED_PHASE_MAX_TILE_SPREAD_PX == 0.35
assert SPLIT_TILED_PHASE_MAX_CHANNEL_SPREAD_PX == 0.15
assert SPLIT_TILED_PHASE_MAX_SHIFT_PX == 2.0
assert SPLIT_MULTISCALE_MIN_ASPECT_RATIO == 2.0
assert SPLIT_MULTISCALE_LOW_MAX_DIMENSION == 1024
assert SPLIT_MULTISCALE_HIGH_MAX_DIMENSION == 2048
assert SPLIT_MULTISCALE_LOW_MIN_RESPONSE == 0.30
assert SPLIT_MULTISCALE_HIGH_MIN_RESPONSE == 0.40
assert SPLIT_MULTISCALE_MAX_CHANNEL_SHIFT_PX == 0.50
assert SPLIT_MULTISCALE_MAX_CHANNEL_SPREAD_PX == 0.50
assert SPLIT_MULTISCALE_MAX_CROSS_SCALE_DELTA_PX == 0.25
assert SPLIT_MULTISCALE_PERIODIC_ALIAS_MIN_HORIZONTAL_PX == 32.0
assert SPLIT_MULTISCALE_PERIODIC_ALIAS_MIN_CHANNELS == 2
assert SPLIT_MULTISCALE_PERIODIC_ALIAS_DOMINANCE == 4.0
assert "coolscanpy.transport.sane" not in sys.modules
"""

    completed = subprocess.run(
        [sys.executable, "-c", script],
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr
